# Generated by Django 5.0.6 on 2025-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
