# Generated by Django 5.0.6 on 2025-04-03 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de celular debe tener exactamente 10 dígitos y no puede ser negativo.', regex='^\\d{10}$')]),
        ),
    ]
