# Generated by Django 5.0.6 on 2025-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='discapacidad',
            field=models.CharField(choices=[('adulto de la tercera edad', 'Tercera-edad'), ('discapacidad fisica permanente', 'Discapacidad-fisica-permanente'), ('discapacidad mental permanente', 'Discapacidad-mental-permanente')], default=None, max_length=50, null=True),
        ),
    ]
