# Generated by Django 5.0.6 on 2025-04-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_usuario_discapacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='condEspecial',
        ),
    ]
