# Generated by Django 5.0.6 on 2025-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_paciente_condespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='asesor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
