# Generated by Django 5.0.6 on 2025-04-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_admin_password_asesor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntoAtencion',
            field=models.CharField(choices=[('sur', 'Sur'), ('centro', 'Centro'), ('norte', 'Norte')], default='sur', max_length=10),
        ),
    ]
