# Generated by Django 5.0.6 on 2025-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_usuario_puntoatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
