# Generated by Django 5.0.6 on 2025-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_paciente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Asesor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
