# Generated by Django 5.0.6 on 2025-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_usuario_totp_confirmed_usuario_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_locked_until',
            field=models.DateTimeField(null=True),
        ),
    ]
