# Generated by Django 5.0.6 on 2025-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_usuario_totp_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
