# Generated by Django 5.0.6 on 2025-07-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_usuario_failed_login_attempts_usuario_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
