# Generated by Django 5.0.6 on 2025-04-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_admin_password_asesor_password'),
        ('services', '0002_puntoatencion_asesoramiento_punto_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoramiento',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario'),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario'),
        ),
        migrations.AddField(
            model_name='reclamarmedicamentos',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario'),
        ),
    ]
