# Generated by Django 5.0.6 on 2025-04-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_asesoramiento_usuario_consultamedica_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoramiento',
            name='general',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asesoramiento',
            name='prioritario',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='general',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='prioritario',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reclamarmedicamentos',
            name='general',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reclamarmedicamentos',
            name='prioritario',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
