# Generated by Django 5.0.6 on 2025-04-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_admin_password_asesor_password'),
        ('services', '0005_alter_asesoramiento_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoramiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_turnos', to='authentication.usuario'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_turnos', to='authentication.usuario'),
        ),
        migrations.AlterField(
            model_name='reclamarmedicamentos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_turnos', to='authentication.usuario'),
        ),
    ]
