# Generated by Django 5.0.6 on 2025-04-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_asesoramiento_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoramiento',
            name='punto_atencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relacionados', to='services.puntoatencion'),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='punto_atencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relacionados', to='services.puntoatencion'),
        ),
        migrations.AlterField(
            model_name='reclamarmedicamentos',
            name='punto_atencion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_relacionados', to='services.puntoatencion'),
        ),
    ]
