# Generated by Django 5.0.6 on 2025-04-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_asesoramiento_general_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoramiento',
            name='punto_atencion',
        ),
        migrations.RemoveField(
            model_name='consultamedica',
            name='punto_atencion',
        ),
        migrations.RemoveField(
            model_name='reclamarmedicamentos',
            name='punto_atencion',
        ),
        migrations.DeleteModel(
            name='PuntoAtencion',
        ),
    ]
