# Generated by Django 5.0.6 on 2025-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_asesoramiento_punto_atencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoramiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='reclamarmedicamentos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=10),
        ),
    ]
