# Generated by Django 5.0.6 on 2025-06-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_asesoramiento_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoramiento',
            name='punto_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='punto_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reclamarmedicamentos',
            name='punto_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
