# Generated by Django 5.0.6 on 2025-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_asesoramiento_punto_atencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='asesoramiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='reclamarmedicamentos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Atendido', 'atendido'), ('Pasado', 'pasado')], default='Pendiente', max_length=15),
        ),
    ]
