# Generated by Django 5.0.6 on 2025-08-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_truno_alter_asesoramiento_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truno',
            new_name='Turno',
        ),
    ]
