# Generated by Django 5.0.6 on 2025-08-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_truno_turno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turno',
            new_name='Truno',
        ),
    ]
